services:
  web:
    build: .
    container_name: car_dealership
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - car_dealership_network

  db:
    image: postgres:15
    container_name: car_dealership_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - car_dealership_network
    restart: always

  redis:
    image: redis:latest
    container_name: car_dealership_redis
    restart: always
    networks:
      - car_dealership_network

volumes:
  db_data:

networks:
  car_dealership_network:
    driver: bridge
